FROM ruby:3.0.0-alpine

RUN  apk add --update --virtual \
    build-dependencies \
    build-base \
    tzdata \
    sqlite-dev

WORKDIR app

COPY . .
RUN gem install bundler
RUN bundle install 

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]